version: '2'
services:
  agnopay:
    build:
      context: ./agnopay-dc
      args:
        - UID
        - GID
    working_dir: /var/www/html
    volumes:
      - ./agnopay:/var/www/html
      - ./agnopay-dc:/usr/src/aidock/build
      - ./agnopay-dc/extra.ini:/usr/local/etc/php/conf.d/extra.ini
      - ./agnopay-dc/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ${HOME}/.composer:/home/appuser/.composer
    env_file: ./agnopay-dc/.env
    depends_on:
      - agnopay-database

  agnopay-database:
    image: mysql:5.7.23
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=main"
      - "MYSQL_USER=user"
      - "MYSQL_PASSWORD=password"
      - "MYSQL_ROOT_PASSWORD=password"

volumes:
  dbdata: